on:
  # pull_request:
  #   branches:
  #     - "*"
  #     - "!gh-pages/*"
  #     - "!releases/*"
  push:
    branches:
      - "*"
      - "!gh-pages/*"
      - "!releases/*"
name: ci

jobs:
  action:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: build.${{ matrix.os }}.${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      # - uses: shogo82148/actions-setup-perl@v1
      #   with:
      #     perl-version: "5.30"
      # - run: perl -V
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: "@tufan-io"
      - run: node --version
      # npm-check has dependencies with vulnerabilities.
      - run: npm i npm-check -g
      - run: npm --version
      - run: git config --global url."https://${{secrets.ACTION_CI}}@github.com".insteadOf ssh://git@github.com
      - run: |
          mkdir demo
          cd demo
          npm init noun-and-verb . -- --demo
          npm run generate
          npm run migrate -- -n initial-migration
          npm run test -- --testTimeout=10000
        env:
          NODE_ENV: dev

